### ISSUE TITLE
Doesn't work with Clojure 1.8

### ISSUE THREAD

**Issue by smaant** [pallet/pallet#353]
```clojure
=> (require 'pallet.api 'pallet.compute 'pallet.configure)
CompilerException java.lang.RuntimeException: Too many arguments to throw, throw expects a single Throwable instance, compiling:(clj_ssh/ssh.clj:242:13) 
```
Updated version of `clj-ssh` is required: https://github.com/hugoduncan/clj-ssh/issues/39
